# config.yaml
server:
  host: "0.0.0.0"  # Address to bind to (0.0.0.0 listens on all interfaces)
  port: 10000      # Port for the Flask app to run on
  debug: false     # Whether to run Flask in debug mode (set to true for development)

model:
  path: "artifacts/seed_pipeline.pkl"  # Path to the trained model file

logging:
  level: "INFO"  # Set the logging level (INFO, DEBUG, ERROR, etc.)
